### PR TITLE
Dockerfile.cuda-torch: do NOT rm /build/core

### PR DESCRIPTION
**Pull request by bertsky**
since we installed core in editable mode!

### CODE REVIEW

**Comment by bertsky** [comment]
Warrants a post-release IMO. Or, if possible, a quick follow-up with v2.69.1.

**Comment by bertsky** [comment]
> Warrants a post-release IMO. Or, if possible, a quick follow-up with v2.69.1.

Or is that even necessary? We could just merge to master – the CD should pick this up and release on Dockerhub, overwriting the current latest and :v2.69.0, right?

**Comment by kba** [comment]
> > Warrants a post-release IMO. Or, if possible, a quick follow-up with v2.69.1.
> 
> Or is that even necessary? We could just merge to master – the CD should pick this up and release on Dockerhub, overwriting the current latest and :v2.69.0, right?

Yep, that should be the case. Not the way it should be done but fine in this case :)

**Review by kba — APPROVED** [review]
LGTM

**Pull request merged**
