### PR TITLE
[wip] update generateDS PAGE API

### PR DESCRIPTION
**Pull request by kba**
Fixing #269.

Just a first test to make sure runtime dependencies are met.

### CODE REVIEW

**Comment by kba** [comment]
>  the typing of the conf attribute

Good point, I could test that conversion also works as expected when using the `set_*` methods.

> why abandon the pc: namespace prefix now?

No reason TBH, generateDS has yet again changed in this regard and it seemed simpler to use no namespace for PAGE (which also reduces noise) than to find out how to reenable the `pc:` namespace. This was the original behavior IIRC. Do you depend on the namespace prefix anywhere?

**Comment by kba** [comment]
> Good point, I could test that conversion also works as expected when using the set_* methods.

It does **not**, e.g. 

```python
el = pcgts.get_Page().get_TextRegion()[0].get_TextLine()[0].get_Word()[0].get_TextEquiv()[0]
el.set_conf('2.0987')
self.assertTrue(isinstance(el.conf, float))
```

fails. :(

**Comment by bertsky** [comment]
> It does **not**, e.g.
> 
> ```python
> el = pcgts.get_Page().get_TextRegion()[0].get_TextLine()[0].get_Word()[0].get_TextEquiv()[0]
> el.set_conf('2.0987')
> self.assertTrue(isinstance(el.conf, float))
> ```
> 
> fails. :(

Okay, so the setter does not convert, but that only affects the in-memory DOM, not its serialization. Badly written processors which do this might also want to see strings there. As long as the getter does convert, I am still satisfied with it.

**Comment by bertsky** [comment]
> > why abandon the pc: namespace prefix now?
> 
> No reason TBH, generateDS has yet again changed in this regard and it seemed simpler to use no namespace for PAGE (which also reduces noise) than to find out how to reenable the `pc:` namespace. 

I see. 

> This was the original behavior IIRC. Do you depend on the namespace prefix anywhere?

No, not anymore: our xmlstarlet/bashlib-based implementations in ocrd_olena and ocrd_im6convert all make an extra effort to determine the namespace prefix and URI of the input and use it.

**Comment by kba** [comment]
> As long as the getter does convert, I am still satisfied with it.

I don't like that it is possible to serialize invalid data. One advantage of an API over direct XML access is that such errors should lead to instant errors.

**Comment by bertsky** [comment]
> Other modules relying on it, like ocrd-cis-align, ocrd-cor-asv-fst-process and ocrd-cor-asv-ann-process might have to be adapted.

Oh wow, you _did_ merge this rather quickly. Now new installations of the above mentioned processors will fail until we adapt them. (I would have preferred making them robust first...)

**Comment by kba** [comment]
> Now new installations of the above mentioned processors will fail

How so? What has changed implementation-wise? You mean your defensive type-casting?

**Comment by bertsky** [comment]
> How so? What has changed implementation-wise? You mean your defensive type-casting?

That `get_conf()` will now deliver floats instead of strings. IIRC only ocrd_keraslm was cautious enough to allow both possibilities.

**Comment by kba** [comment]
I thought one point of https://github.com/OCR-D/core/issues/269 was to fix this. I had an idea for systematically testing all module projects in ocrd_all, I'll implement it and see what this might have broken.

**Pull request merged**
