### PR TITLE
bashlib: make input-files n-ary

### LINKED ISSUE #1027: bashlib: implement input-files for multiple input fileGrps
Currently, we have
https://github.com/OCR-D/core/blob/de084535e18a2f2fa9293085cda4431abfe2e191/ocrd/ocrd/processor/base.py#L269
as an alias for the mono-valued variant of the generic
https://github.com/OCR-D/core/blob/de084535e18a2f2fa9293085cda4431abfe2e191/ocrd/ocrd/processor/base.py#L294
and we delegate to the former from bashlib via
https://github.com/OCR-D/core/blob/de084535e18a2f2fa9293085cda4431abfe2e191/ocrd/ocrd/cli/bashlib.py#L80-L119
which can then be used in bash processors after
https://github.com/OCR-D/core/blob/de084535e18a2f2fa9293085cda4431abfe2e191/ocrd/ocrd/lib.bash#L241-L256
in the form of `ocrd__input_file num feat` (where `num` is the physical page number and `feat` is `url|ID|mimetype|pageId`).

So for processors that (can) consume multiple input fileGrps at once, like [ocrd-pagetopdf](https://github.com/UB-Mannheim/ocrd_pagetopdf/issues/21), we need to generalize. 

And because we would not want to break existing usage, and bash's data structures are poor (associative arrays are not recursive), I suggest exposing an additional variable+function `ocrd__input_files num feat` which yields a list of results (one per fileGrp).

### PR DESCRIPTION
**Pull request by bertsky**
fixes #1027

### CODE REVIEW

**Comment by bertsky** [comment]
Note: usage is as follows:
- the builtin function `ocrd__input_file` is still available (and I kept the name – no plural), but **if there are 2 input fileGrps**, then all its result will be a (single-quote delimited) **list**, e.g. `[url]='file1.xml file2.xml' [ID]='id_file1 id_file2' ...`
- whenever it needs to be called, one should therefore encapsulate its results in a (non-associative) **array variable** and without extra quotes, e.g. `in_file=($(ocrd__input_file 3 url))`
- this will yield the first fileGrp's results on index 0, which in bash will always be the same as if you referenced the array without index (so code does not need to be changed much), e.g. `test -f $in_file`
- if there is a second fileGrp, then its result will have to be fetched from index 1, e.g. `test -f ${in_file[1]}`

For a full example, see https://github.com/UB-Mannheim/ocrd_pagetopdf/pull/22

**Comment by bertsky** [comment]
> For a full example, see [UB-Mannheim/ocrd_pagetopdf#22](https://github.com/UB-Mannheim/ocrd_pagetopdf/pull/22)

Since I will probably [rewrite ocrd-pagetopdf](https://github.com/UB-Mannheim/ocrd_pagetopdf/pull/22#issuecomment-1488376858) to not use multiple input fileGrps anymore, we could use another example for this capability.

How about some generic bashlib processor in tests which merely does a `cp` from input to output? (Or for multiple input fileGrps `cp` the file from the last grp, respectively.)

**Review by kba — APPROVED** [review]
That's a good way to ensure backwards-compatibility and support multiple input file groups, even [if they're not necessary for ocrd_pagetopdf anymore](https://github.com/UB-Mannheim/ocrd_pagetopdf/pull/22#issuecomment-1488376858).

**Comment by kba** [comment]
> Note: usage is as follows:

Can you add this as a comment to `ocrd__input_file` pls?

**Comment by bertsky** [comment]
> Can you add this as a comment to `ocrd__input_file` pls?

https://github.com/bertsky/core/commit/2b51a5e0db22636eccf8ad8ba727657436aece3f

**Comment by bertsky** [comment]
sorry for the noise – was too lazy to do it locally

**Comment by bertsky** [comment]
fixes #413

**Comment by bertsky** [comment]
> fixes #413

it's really strange: I cannot link to this issue (in text or directly in `development`). Neither in the opposite direction (from issue to this PR). Another GH quirk?

**Comment by kba** [comment]
> > fixes #413
> 
> it's really strange: I cannot link to this issue (in text or directly in `development`). Neither in the opposite direction (from issue to this PR). Another GH quirk?

Apparently so, I cannot link them either...

**Comment by bertsky** [comment]
Finally got it working – ready to be merged :sweat:

**Comment by bertsky** [comment]
CI: now only macos failure remains.

**Comment by kba** [comment]
I struggle to fix the macos test, now it's complaining that `bash` is too old, I installed bash `5.1.8` via homebrew but that's apparenly not the first `bash` in `$PATH`. When I try to debug it via SSH, it restarts the job but does not offer an SSH session. So I'll have to debug that further in the context of the other failing macos tests.

**Comment by bertsky** [comment]
@kba can we please make a quick release 2.50 out of the current master? Remember that in https://github.com/UB-Mannheim/ocrd_pagetopdf/pull/22 I had to require a new 2.50 for the n-ary bashlib fix.

**Pull request merged**
