### PR TITLE
Remove unneeded dependency python3-pip

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Review by kba — APPROVED** [review]

**Comment by kba** [comment]
We probably even only need `python3-venv` because it implies `python3` doesn't it?

**Comment by stweil** [comment]
That's right, but the superfluous `python3` won't cause installation of unneeded software (while `python3-pip` would, well, only about 1 .2 MB).

**Comment by bertsky** [comment]
Wait, can you show me proof / documentation that's true? (I often see the case that `pip` or `pip3` in a venv points to the preinstalled version from the host system, not the venv.)

**Comment by stweil** [comment]
I haven't installed `python3-pip` on any of our systems where I have built OCR-D (Linux, macOS, Debian, Ubuntu, x86_64, arm, aarch64, Python 3.6, 3.7, 3.8, 3.9). `pip` or `pip3` is always a small script with less than 300 bytes .

**Pull request merged**
