### PR TITLE
ocrd_page: more flexible __hash__

### PR DESCRIPTION
**Pull request by kba**
fixes https://github.com/OCR-D/ocrd_segment/issues/45

### CODE REVIEW

**Review by bertsky — APPROVED** [review]
Excellent, thanks!

**Comment by stweil** [comment]
@kba, I still get issue OCR-D/ocrd_segment#45 after applying this pull request locally.

**Comment by bertsky** [comment]
> I still get issue [OCR-D/ocrd_segment#45](https://github.com/OCR-D/ocrd_segment/issues/45) after applying this pull request locally.

@stweil are you sure you also _installed_ it into the right (sub-)venv, too?

**Comment by stweil** [comment]
> @stweil are you sure you also installed it into the right (sub-)venv, too?

I had just updated my comment. I am sure that `make all` did update venv, but not the sub venvs.

**Review by stweil — APPROVED** [review]
The patch fixes issue OCR-D/ocrd_segment#45, but requires a fresh `make all` or a manual update of the `headless-tf1`sub venv.

**Pull request merged**
