### PR TITLE
fix __init__ docstring order/markup

### PR DESCRIPTION
**Pull request by bertsky**
- re-instate item for coordinate conversion utils (not first any longer)
- improve RST indentation

### CODE REVIEW

**Comment by bertsky** [comment]
@kba would it be ok if I added more commits in accordance with #254?

**Comment by bertsky** [comment]
From top-level (core) README.md:
> ### ocrd
> Contains all of the above and in addition decorators for creating OCR-D processors and CLI.

Shouldn't that read `installs all of the above`? (When importing, I still have to use the other packages, so they are not _contained_ in `ocrd`.) 

Also, shouldn't that read "decorators `and classes` for creating OCR-D processors and CLI"?

**Comment by kba** [comment]
> Also, shouldn't that read "decorators and classes for creating OCR-D processors and CLI"?

Yes.

> Shouldn't that read installs all of the above? (When importing, I still have to use the other packages, so they are not contained in ocrd.)

Also true. Initially, I wanted to expose all the `ocrd_*` functionality directly from `ocrd/__init__.py` so you could do `from ocrd.utils import logging` install of `from ocrd_utils import logging` or even `from ocrd import logging`. But that got confusing and unwieldy.

**Comment by kba** [comment]
> @kba would it be ok if I added more commits in accordance with #254?

Very okay that would be :) I just would not prioritize it before the dev workshop next week. But documentation is always welcome!

**Comment by bertsky** [comment]
Okay, I will change that formulation in another commit then. 

And do you generally concur with `s/module/package/` in this scope?

**Comment by kba** [comment]
> And do you generally concur with `s/module/package/` in this scope?

In usage, they are modules but they are distributed as separate packages. In the top-level README, "package" makes more sense, yes.

**Comment by bertsky** [comment]
Exactly. I had this surprise effect when I first saw your restructuring that it's really "one repo, multiple packages". And since in Python, all packages are also modules...

**Comment by bertsky** [comment]
Done. Fixes #254 – thankfully, you had already added most of the `__init__` docstrings by now.

**Comment by kba** [comment]
Thanks!

**Pull request merged**
