### PR TITLE
Delete files

### PR DESCRIPTION
**Pull request by kba**
Adds a command `ocrd workspace remove` that allows removing files, with the resp. `remove_files` commands on workspace and METS level.

Also a few fixes related to handling of local filenames for mets:file

### CODE REVIEW

**Comment by kba** [comment]
> b027faa: Is this related to #96 and my fix #266 by any chance?

Yes, it's related. The proper fix is to harmonize the URL handling throughout, b027faa is yet another band-aid I'm afraid.

**Comment by bertsky** [comment]
> Yes, it's related. The proper fix is to harmonize the URL handling throughout, [b027faa](https://github.com/OCR-D/core/commit/b027faafafdfb29290435ed4f55c2c1a8cc85823) is yet another band-aid I'm afraid.

Um, does that mean b027faa is temporary? And does this mean #266 is going to be adopted?

**Comment by kba** [comment]
Yeah, https://github.com/OCR-D/core/commit/b027faafafdfb29290435ed4f55c2c1a8cc85823 is temporary. I have another branch for fixing #96 and #227 that should hopefully render #266 unnecessary.

**Comment by bertsky** [comment]
Understood – thanks for clarifying!

**Pull request merged**
