### PR TITLE
replace --agent-type with subcommand, #1032, #1085

### PR DESCRIPTION
**Pull request by kba**
- Instead of an option `--agent-type`, implement the behavior as subcommands, i.e.

```
ocrd-foo --agent-type worker ...
```

becomes

```
ocrd-foo worker ...
```

Also removes the exception handling because it does not actually handle the exceptions, just stringifies them and we want full stack traces if something goes wrong.

### CODE REVIEW

**Comment by MehmedGIT** [comment]
Initially, I did not see a reason why we would need that change. However, now when I think about it, this refines the way we handle the `worker` and `server` subcommands. The `--queue` option is exclusive for the `worker` and the `--address` option is exclusive for the `server`.

So `ocrd-* worker --help` and `ocrd-* server --help` could have a more meaningful output for the general user. 

Currently, `ocrd-* --help` is still lacking the `--address` flag and the additional processing worker flags (`--create-queue` and `--queue-connect-attempts`) added in #1075.

```
Options for Processing Worker server:
  --queue                         The RabbitMQ server address in format
                                  "amqp://{user}:{pass}@{host}:{port}/{vhost}"
                                  [amqp://admin:admin@localhost:5672]
  --database                      The MongoDB server address in format
                                  "mongodb://{host}:{port}"
                                  [mongodb://localhost:27018]
  --type                          type of processing: either "worker" or "server"

```

**Comment by MehmedGIT** [comment]
I could already push here the adaptation changes needed in the `ocrd network` to use the subcommands.

**Comment by MehmedGIT** [comment]
The bash library should still be adapted appropriately. Currently, it still accepts `--type`.

**Comment by kba** [comment]
> So `ocrd-* worker --help` and `ocrd-* server --help` could have a more meaningful output for the general user.

OK, so how about three `--help` variants. One for the general CLI which lists the `worker`/`server` subcommands but omits the sections `Options for Processing Worker:` and `Options for Processor Server:`. Then one for `ocrd-* worker --help` which lists only those options and one for `ocrd-* server` which lists those options plus the general `Options for processing`?

**Comment by MehmedGIT** [comment]
That would be even better!

**Comment by kba** [comment]
> now to fix the errors I've introduced apparently :/

Debug echo&exit was still in there 🙃 time for weekend.

**Review by MehmedGIT — APPROVED** [review]

**Pull request merged**
