### PR TITLE
remove logfile from bashlib

### PR DESCRIPTION
**Pull request by MehmedGIT**
Fix for #1119

### CODE REVIEW

**Review by kba — APPROVED** [review]
Yes, that was an intermediate state I forgot to fix. LGTM

**Comment by bertsky** [comment]
@kba @MehmedGIT the `--log-filename` is still in the general CLI though. It is still used for the processing worker (and the server), but comes in via configuration option `NetworkLoggingDirs.PROCESSING_JOBS` instead of the CLI. Since it was on the main processor CLI, I thought it was a mistake and added it to #1240 in https://github.com/OCR-D/core/pull/1240/commits/4f88f1d209bc86cdaea031ae9b2bda685e4f8fba. Do we really want that, though? If yes, then I must reinstante the bashlib side as well.

**Comment by MehmedGIT** [comment]
@bertsky The `ocrd_network` logging should have nothing to do with the `--log-filename` flag coming from the general CLI. That is not passed down to the `ProcessingWorker` instance. I think that is a leftover from old code and should be removed. Unless the user wants to forward their logs to a separate file with the CLI - in that case it is fine.

We have structured logging in the `ocrd_network`. `NetworkLoggingDirs.PROCESSING_JOBS` is just a directory constant for processing job logs. Each processing job log file is stored inside with a unique name: `{job_id}.log`. When the ProcessingWorker invokes a processing job with `run_processor` or `run_cli`, the ProcessingWorker passes the unique job log file name as a parameter. Each ProcessingWorker also has its log file (`f"{AgentType.PROCESSING_WORKER}.{pid}.{processor_name}.log"`) and these are stored under `NetworkLoggingDirs.PROCESSING_WORKERS`.

**Comment by bertsky** [comment]
I'll take that as a `yes` and will re-instante the option for bashlib (but only for the processing case, not networking).

**Comment by MehmedGIT** [comment]
> (but only for the processing case, not networking)

Yes!

**Pull request merged**
