### PR TITLE
Extension to the Processing Server (#974)

### PR DESCRIPTION
**Pull request by MehmedGIT**
This is the required temporal extension for the processing server to download the ocrd all tool json when the server is started. Implemented separately from #974, to not block #974 anymore and continue the required changes here.

### CODE REVIEW

**Comment by bertsky** [comment]
@MehmedGIT here it would make sense rebasing the PR on the `dev-processing-broker` branch, too.

**Comment by tdoan2010** [comment]
@MehmedGIT I think the code from this PR was already merged in another PR. So, we can close this, or?

**Comment by bertsky** [comment]
BTW, we still need to add `ocrd_network` to the Makefile's `BUILD_ORDER`, otherwise `make install` will not install it.

**Comment by kba** [comment]
> BTW, we still need to add `ocrd_network` to the Makefile's `BUILD_ORDER`, otherwise `make install` will not install it.

`ocrd_network` is in `BUILD_ORDER` or did I miss something?

https://github.com/OCR-D/core/blob/b7130307ce68c5f074c1ceea24b66ae9ee9ef289/Makefile#L12

**Comment by bertsky** [comment]
> `ocrd_network` is in `BUILD_ORDER` or did I miss something?

Oops, I was using the wrong branch locally and got confused. Sorry for the noise!

**Comment by MehmedGIT** [comment]
This PR is no longer needed since #1030 already implemented the required extension.

**Pull request closed without merging**
