### PR TITLE
workspace_bagger: fixes for bag and spill with bagits having mets-name other than mets.xml

### PR DESCRIPTION
**Pull request by joschrew**
currently bagging and spilling with bags not containing mets.xml but a different name for the mets don't work. This pr should fix this and make it possible to create bagits and to convert (spill) workspaces from bagits where the metsfile-name is changed and Ocrd-Mets is set in bag-info.txt

### CODE REVIEW

**Comment by bertsky** [comment]
Which of the bagger issues should this fix exactly?

**Comment by joschrew** [comment]
I didn't fill issues for that if you mean that with your question. Do I have to do that before I make a pull request?

There are ocrd-zipfiles which do not have a data/mets.xml but for example data/foo.xml which is the metsfile. In this cases in bag-info.txt `Ocrd-Mets` has to be set to `data/foo.xml`. This is valid according to the specs. But if you have such an ocrd-zipfile and try to spill it with workspace_bagger.py spill() with the current version of the code, it throws an error.
If you try to create such a ocrd-zip file with workspace_bagger.py bag() it does not work because `Ocrd-Mets` is not set in bag-info.txt to `data/foo.xml` as expected.

**Comment by kba** [comment]
> I didn't fill issues for that if you mean that with your question. Do I have to do that before I make a pull request? Or maybe my this PullRequest's text/comment has to be changed?

No, we had a private discussion on this and I agreed that the behavior @joschrew observed is a bug and asked him to fix it.

> 
> There are ocrd-zipfiles which do not have a data/mets.xml but for example data/foo.xml which is the metsfile. In this cases in bag-info.txt `Ocrd-Mets` has to be set to `data/foo.xml`. This is valid according to the specs. But if you have such an ocrd-zipfile and try to spill it with workspace_bagger.py spill() with the current version of the code, it throws an error. If you try to create such a ocrd-zip file with workspace_bagger.py bag() it does not work because `Ocrd-Mets` is not set in bag-info.txt to `data/foo.xml` as expected.

:+1:

**Review by kba — APPROVED** [review]

**Comment by bertsky** [comment]
Thanks for explaining. Sounds a lot like https://github.com/OCR-D/core/issues/363 to me.

**Pull request merged**
