### PR TITLE
ocrd_utils.image: fix bg tuple vs scalar (depending on mode)

### PR DESCRIPTION
**Pull request by bertsky**
as a workaround for python-pillow/Pillow#4925

### CODE REVIEW

**Review by kba — APPROVED** [review]
LGTM AFAICT. A test that triggers the situation that led to the error would be useful.

**Comment by bertsky** [comment]
> A test that triggers the situation that led to the error would be useful.

That could only be provided by suitable images. Perhaps we should create them artificially via `PIL.Image.new`. Or be extended existing tests on real images after converting them to other modes on the fly.

The error was triggered by 32-bit (mode `I` or `F`) or 16-bit (mode `I;16`) images.

**Comment by kba** [comment]
> > A test that triggers the situation that led to the error would be useful.
> 
> That could only be provided by suitable images. Perhaps we should create them artificially via `PIL.Image.new`. Or be extended existing tests on real images after converting them to other modes on the fly.
> 
> The error was triggered by 32-bit (mode `I` or `F`) or 16-bit (mode `I;16`) images.

I've added a tiny test that fails with https://github.com/python-pillow/Pillow/issues/4925 in master but should succeed here 🤞

**Comment by bertsky** [comment]
> I've added a tiny test that fails with [python-pillow/Pillow#4925](https://github.com/python-pillow/Pillow/issues/4925) in master but should succeed here :crossed_fingers:

Excellent!

**Pull request merged**
