### PR TITLE
Remove unneeded pass statements

### PR DESCRIPTION
**Pull request by stweil**
This fixes warnings from LGTM:

    Unnecessary 'pass' statement.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
There are [many more warnings and recommendations](https://lgtm.com/projects/g/OCR-D/core/alerts).

**Comment by kba** [comment]
That file is auto-generated from XSD. It's not perfect code but consistent. We're using [pylint to check code style](https://github.com/OCR-D/core/blob/master/.pylintrc).

Good point though that we should re-enable the `unused XYZ` warnings, I've disabled it at some point because they were mostly noise.

**Comment by kba** [comment]
@stweil Is there a way to filter the warnings about the file `ocrd_page_generateds.py` on lgtm.com?

**Comment by stweil** [comment]
Pull request #214 should do that. It excludes the whole file for LGTM.

**Comment by stweil** [comment]
Closing this PR as it was for a generated file which should be ignored.

**Comment by stweil** [comment]
The generated file was renamed, so the LGTM rules need an update. I'll send a PR.

**Pull request closed without merging**
