### PR TITLE
ocrd_utils: adapt to newer importlib.resources API

### LINKED ISSUE #995: ocrd_utils.resource_string: importlib.resources.read_binary deprecated
According to [this](https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy), we have to migrate to `importlib.resources.files` API.

https://github.com/OCR-D/core/blob/0c6208154b15e22e24b74ec51a42a2d7d8074751/ocrd_utils/ocrd_utils/package_resources.py#L47

### PR DESCRIPTION
**Pull request by bertsky**
fixes #995

### CODE REVIEW

**Review by kba — APPROVED** [review]

**Comment by bertsky** [comment]
[Ouch](https://app.circleci.com/pipelines/github/OCR-D/core/1668/workflows/a2dab04d-a8fa-4de7-bab4-5dbd2c7cf731/jobs/6113)!

So on Py38 we already have importlib.resources, but not the new `files` API!

**Comment by bertsky** [comment]
> So on Py38 we already have importlib.resources, but not the new `files` API!

To fix this we therefore must replace the `<3.8` with a `<=3.8` (or with `<3.9`) in
https://github.com/OCR-D/core/blob/432d852bfd6be7b171042422ebbb451fc0f64c72/ocrd_utils/requirements.txt#L7

**Comment by kba** [comment]
I will fix it once I get the docker images built.

**Comment by bertsky** [comment]
> I will fix it once I get the docker images built.

What do you mean? Merge #986?

The problem I just described _is_ affecting the Docker build.

**Comment by kba** [comment]
> > I will fix it once I get the docker images built.
> 
> What do you mean? Merge #986?

Yes

> The problem I just described _is_ affecting the Docker build.

I meant, I will debug this in the context of #986.

**Pull request merged**
